import { createFileRoute, Link } from "@tanstack/react-router"
import { getOperationalWorkspace } from "../features/operations/server"
import { Icon } from "../components/app-shell"

export const Route = createFileRoute("/overview")({ loader: () => getOperationalWorkspace(), component: Overview })
function Overview() {
  const data = Route.useLoaderData()
  const active = data.pipelines.filter((p) => p.runtime.active).length
  const connected = data.pipelines.filter((p) => p.runtime.connected).length
  const messages = data.pipelines.reduce((sum, p) => { const value = p.runtime.stats?.input; return sum + (value && typeof value === "object" && "received" in value && typeof value.received === "number" ? value.received : 0) }, 0)
  return <div className="workspace-page"><header className="page-header"><div><span className="eyebrow">Operate</span><h1>Overview</h1><p>See the state of your pipelines and runtime at a glance.</p></div><Link className="button button-primary" to="/pipelines">Open pipelines</Link></header><div className="metric-row"><div className="metric-card"><span>Pipelines</span><strong>{data.pipelines.length.toString().padStart(2, "0")}</strong><small>Managed by Porcelain</small></div><div className="metric-card"><span>Running</span><strong>{active.toString().padStart(2, "0")}</strong><small>{connected} connected</small></div><div className="metric-card"><span>Messages received</span><strong>{new Intl.NumberFormat().format(messages)}</strong><small>Across visible streams</small></div><div className="runtime-card"><span className={"status-dot " + (data.connectReady ? "online" : "offline")} /><div><strong>{!data.connectReachable ? "Runtime unreachable" : data.connectReady ? "Connect ready" : "Connect degraded"}</strong><small>Redpanda Connect · localhost:4195</small></div></div></div><div className="content-grid"><section className="panel"><div className="panel-header"><div><h2>Pipelines</h2><p>Current runtime state from Redpanda Connect.</p></div></div><div className="pipeline-list">{data.pipelines.length ? data.pipelines.map((p) => <Link className="pipeline-row" key={p.id} to="/pipelines/$pipelineId" params={{ pipelineId: p.id }}><span className="pipeline-icon"><Icon name="pipeline" /></span><span className="pipeline-main"><strong>{p.name}</strong><code>{p.id}</code></span><span className={"status " + (p.runtime.active ? "status-running" : p.runtime.connected ? "status-inactive" : "status-disconnected")}><span className="status-dot" />{p.runtime.active ? "Running" : p.runtime.connected ? "Stopped" : "Disconnected"}</span></Link>) : <div className="empty-inline">No pipelines yet.</div>}</div></section><aside className="panel detail-panel"><div className="detail-heading"><div className="pipeline-icon large"><Icon name="activity" /></div><div><span className="eyebrow">Activity</span><h2>Recent events</h2></div></div>{data.activity.length ? <div className="activity-list">{data.activity.slice(0, 10).map((event) => <div className="activity-item" key={event.id}><span className="status-dot online" /><div><strong>{event.detail}</strong><small>{event.pipelineName ?? "Porcelain"} · {new Date(event.timestamp).toLocaleString()}</small></div></div>)}</div> : <div className="detail-placeholder"><p>Runtime events will appear here as pipelines change state.</p></div>}</aside></div></div>
}
