import { createFileRoute, Link } from "@tanstack/react-router"
import { getOperationalWorkspace } from "../features/operations/server"
import { Icon } from "../components/app-shell"

type OperationalWorkspace = Awaited<ReturnType<typeof getOperationalWorkspace>>
type OperationalPipeline = OperationalWorkspace["pipelines"][number]
export const Route = createFileRoute("/runtime")({ loader: () => getOperationalWorkspace(), component: Runtime })
function Runtime() {
  const data = Route.useLoaderData()
  return <div className="workspace-page"><header className="page-header"><div><span className="eyebrow">Operate</span><h1>Runtime</h1><p>Live state and telemetry from Redpanda Connect.</p></div><span className={"status " + (data.connectReady ? "status-running" : "status-disconnected")}><span className="status-dot" />{!data.connectReachable ? "Unreachable" : data.connectReady ? "Ready" : "Degraded"}</span></header><div className="metric-row"><div className="metric-card"><span>Streams</span><strong>{data.pipelines.length}</strong><small>Porcelain-managed</small></div><div className="metric-card"><span>Active</span><strong>{data.pipelines.filter((p: OperationalPipeline) => p.runtime.active).length}</strong><small>Running now</small></div><div className="metric-card"><span>Connected</span><strong>{data.pipelines.filter((p: OperationalPipeline) => p.runtime.connected).length}</strong><small>Linked to Connect</small></div><div className="runtime-card"><span className={"status-dot " + (data.connectReady ? "online" : "offline")} /><div><strong>{data.connectReachable ? "Redpanda Connect" : "Connection unavailable"}</strong><small>localhost:4195</small></div></div></div><section className="panel"><div className="panel-header"><div><h2>Live streams</h2><p>Status and uptime from the runtime.</p></div></div><div className="pipeline-list">{data.pipelines.map((p: OperationalPipeline) => <Link className="pipeline-row" key={p.id} to="/pipelines/$pipelineId" params={{ pipelineId: p.id }}><span className="pipeline-icon"><Icon name="pulse" /></span><span className="pipeline-main"><strong>{p.name}</strong><code>{p.connectStreamId ?? "not linked"}</code></span><span className="row-runtime">{p.runtime.uptime}</span><span className={p.runtime.active ? "status status-running" : p.runtime.connected ? "status status-inactive" : "status status-disconnected"}><span className="status-dot" />{p.runtime.active ? "Running" : p.runtime.connected ? "Stopped" : "Disconnected"}</span></Link>)}</div></section></div>
}
