import { createFileRoute } from "@tanstack/react-router"
import { useMemo, useState, type ChangeEvent } from "react"
import { getOperationalWorkspace } from "../features/operations/server"

type OperationalWorkspace = Awaited<ReturnType<typeof getOperationalWorkspace>>
type OperationalPipeline = OperationalWorkspace["pipelines"][number]
type SchemaEntry = { pipeline: string; type: string }
export const Route = createFileRoute("/schemas")({ loader:()=>getOperationalWorkspace(), component:Schemas })
function Schemas(){const {pipelines}=Route.useLoaderData();const entries=useMemo(()=>pipelines.flatMap((p: OperationalPipeline)=>[p.authoring.input,...(p.authoring.processors??[]),p.authoring.output].flatMap(config=>Object.keys(config).map(type=>({pipeline:p.name,type})))),[pipelines]);const [query,setQuery]=useState("");const filtered=entries.filter((e: SchemaEntry)=>e.type.includes(query.toLowerCase())||e.pipeline.toLowerCase().includes(query.toLowerCase()));return <div className="workspace-page"><header className="page-header"><div><span className="eyebrow">Manage</span><h1>Event schemas</h1><p>Observed component types across pipelines. Schema Registry is not configured in this local runtime.</p></div></header><section className="panel"><div className="panel-header"><div><h2>Observed types</h2><p>{entries.length} component references</p></div><label className="input-search"><input aria-label="Filter schemas" placeholder="Filter types" value={query} onChange={(e: ChangeEvent<HTMLInputElement>)=>setQuery(e.target.value)} /></label></div><div className="pipeline-list">{filtered.map((e: SchemaEntry,i: number)=><div className="pipeline-row" key={e.pipeline+e.type+i}><span className="pipeline-icon"><span className="mono">{e.type.slice(0,1).toUpperCase()}</span></span><span className="pipeline-main"><strong>{e.type}</strong><code>{e.pipeline}</code></span></div>)}</div></section></div>}
